#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

if [ "$1" != "" ]
    then airfoil=$1
else
    echo Missing airfoil argument!
fi

if [ "$2" != "" ]
    then alpha=$2
else
    echo Missing angle of attack argument!
fi

if [ "$3" != "" ]
  then mach=$3
else
  echo Missing mach number argument!
fi

./Allrun.pre $airfoil $alpha $mach

#start=$(date +%s.%N)

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

#end=$(date +%s.%N)
#runtime=$(python -c "print(${end} - ${start})")
#
#echo "Runtime was $runtime"
#
#runApplication foamToVTK -latestTime -no-boundary -overwrite
#rm -f log.foamToVTK
#------------------------------------------------------------------------------
